---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydemo
      version: v1
  template:
    metadata:
      labels:
        app: mydemo
        version: v1
    spec:
      containers:
        - name: mydemo
          image: dormidos/demo:v1.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mydemo
spec:
  ports:
  - name: http
    port: 3751
    protocol: TCP
    targetPort: 5000
  selector:
    app: mydemo
    version: v1

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mydemo
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/client-max-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: mydemo.dormidoshm.net
    http:
      paths:
      - backend:
          service:
            name: mydemo
            port:
              number: 5000
        path: /
        pathType: Prefix

