---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydemo
      version: v2
  template:
    metadata:
      labels:
        app: mydemo
        version: v2
    spec:
      containers:
      - name: mydemo
        image: dormidos/demo:v2.0
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mydemo2
spec:
  ports:
  - name: http
    port: 3752
    protocol: TCP
    targetPort: 5000
  selector:
    app: mydemo
    version: v2

